Fix StripeCreditCard#try_void
`Payment::Cancellation#cancel` calls StripeCreditCard#try_void`.

When not using Payment Intents (ie. when using Elements or V2 API),
after calling `try_void`, the former makes the following call:

  payment.send(:handle_void_response, response)

which is already called by `payment.void_transaction!`, making
the two incompatible, as `#handle_void_response` cannot be called
twice here - it would raise the error:

  NoMethodError: undefined method `success?' for true:TrueClass

Under the hood `#void_transaction!` calls `payment_method.void`,
so the new code is rather equivalent to the previous one. The
only relevant feature we're losing is that `#void_transaction!`
wraps the call in a `protect_from_connection_error` block.

The modified integration spec verifies that an order created with
Elements can be cancelled without raising the error mentioned
above.